#file definizione modelli per linguaggio Lisp (AutoCAD/progeCAD o compatibili)

[Modelli Lisp]
c=;;;------------------------------------------------------------------;\n;;;       Function: |\n;;;\n;;;    Description:\n;;;\n;;;      Arguments:\n;;;\n;;; Returned Value:\n;;;\n;;;          Usage:\n;;;------------------------------------------------------------------;\n
cond=(cond\n  ((|) )\n  (t )\n);endcond
command=(command "|")
def=(defun | ( / )\n\t\n\n);enddef
defc=(defun C:| ( / )\n\t\n\n);enddef
defun=(defun | ( / )\n\t\n\n);enddef
defunc=(defun C:| ( / )\n\t\n\n);enddef
getvar=(getvar "|")
princ=(princ "|")
print=(print "|")
prin1=(prin1 |)
polar=(polar '(|) )
prompt=(prompt "|")
s=(setq |)
setq=(setq |)
setvar=(setvar "|" )
strcat=(strcat |)
ssget=(ssget "_|" '())
substr=(substr "|" )
if=(if |\n\t(progn\n\t)\n);endif
ifelse=(if |\n\t(progn\n\t)\n\t(progn ;else\n\t)\n);endif
ifnot=(if (not |)\n\t(progn\n\t)\n\t(progn ;else\n\t)\n);endif
itoa=(itoa |)
line=(command "_line" "|" "" "")
arc=(command "_arc" "|" "" "")
circle=(command "_circle" "|" "")
pline=(command "_pline" "|" "" "")
point=(command "_point" |)
erase=(command "_erase" "_all" "")
zoom=(command "_zoom" "_e")
abs=(abs |)
alert=(alert "|")
angle=(angle '(|) '())
apply=(apply '| '(|))
append=(append '(|) '(|))
ascii=(ascii "|")
assoc=(assoc '| )
atan=(atan '| )
atof=(atof "|")
atoi=(atoi "|")
atoms-family=(atoms-family |)
boundp=(boundp |)
car=(car |)
cadr=(cadr |)
caddr=(caddr |)
cons=(cons '| )
chr=(chr |)
open=(setq idf (open | "r"))\n\t\n(close idf)
entmake=(entmake |)
entmod=(entmod |)
while=(while |\n\t\n)
write-line=(write-line "|" idf)
foreach=(foreach | '()\n\t\n)
repeat=(repeat |\n\t\n)
read-line=(read-line |)
reverse=(reverse |)
distance=(distance | )
todo=;TODO: |
Modelli HTML Default=[#abbrevfile:abbrev.properties#]
