#file definizione modelli per linguaggio Lisp (AutoCAD/progeCAD o compatibili)

[Modelli Lisp]
c=;;;------------------------------------------------------------------;\n;;;       Function: |\n;;;\n;;;    Description:\n;;;\n;;;      Arguments:\n;;;\n;;; Returned Value:\n;;;\n;;;          Usage:\n;;;------------------------------------------------------------------;\n
cond=(cond\n\t((|) )\n\t(t )\n);endcond
command=(command "|")
cmd=(command "|")
def=(defun | ( / ss i e ent )\n\t\n\n);enddef
defc=(defun C:| ( / )\n\t\n\n);enddef
defun=(defun | ( / )\n\t\n\n);enddef
defunc=(defun C:| ( / )\n\t\n\n);enddef
getvar=(getvar "|")
princ=(princ "|")
print=(print |)
prin1=(prin1 |)
polar=(polar '(|) )
prompt=(prompt "|")
s=(setq |)
ss=(setq i 0)\n(while (setq e (ssname ss i))\n\t|\n\t(setq i (1+ i))\n)
setq=(setq |)
setvar=(setvar "|" )
strcat=(strcat |)
ssget=(ssget "X" '(|))
substr=(substr "|" )
if=(if |\n\t\n);endif
ifp=(if |\n\t(progn\n\t)\n);endif
ifpp=(if |\n\t(progn\n\t)\n\t(progn ;else\n\t)\n);endif
ifelse=(if |\n\t(progn\n\t)\n\t(progn ;else\n\t)\n);endif
ifnot=(if (not |)\n\t(progn\n\t)\n\t(progn ;else\n\t)\n);endif
not=(not |)
itoa=(itoa |)
inters=(inters|)
line=(command "_line" "|" "" "")
arc=(command "_arc" "|" "" "")
circle=(command "_circle" "|" "")
pline=(command "_pline" "|" "" "")
point=(command "_point" |)
erase=(command "_erase" "_all" "")
zoom=(command "_zoom" "_e")
abs=(abs |)
alert=(alert "|")
angle=(angle '(|) '())
apply=(apply '| '())
append=(append '(|) '())
ascii=(ascii "|")
assoc=(assoc '| )
atan=(atan '| )
atof=(atof "|")
atoi=(atoi "|")
atomsfamily=(atoms-family |)
boundp=(boundp |)
car=(car |)
cadr=(cadr |)
caddr=(caddr |)
cons=(cons '| )
chr=(chr |)
open=(setq idf (open | "r"))\n\t\n(close idf)
entmake=(entmake |)
entmod=(entmod |)
eq=(eq|)
equal=(equal|)
expt=(expt|)
while=(while |\n\t\n)
writeline=(write-line "|" idf)
for=(foreach | '()\n\t\n)
foreach=(foreach | '()\n\t\n)
repeat=(repeat |\n\t\n)
readline=(read-line |)
reverse=(reverse |)
distance=(distance|)
nth=(nth|)
lefttrim=(vl-string-left-trim|)
trim=(vl-string-trim|)
search=(vl-string-search|)
dcl=(setq fdcl "myfile.dcl")\n(setq dcl_id (load_dialog fdcl))\n(new_dialog "myDialog" dcl_id)\n(setq userclick (start_dialog))\n(unload_dialog dcl_id)\n
getcolor=(setq color (cdr (assoc 62 |)))
getlayer=(setq layer (cdr (assoc 8 |)))
todo=;TODO: |
i+1=(setq i (1+ i))
i++=(setq i (1+ i))
i-1=(setq i (1- i))
i--=(setq i (1- i))
tblsearch=(tblsearch "|" "")
Modelli HTML Default=[#abbrevfile:abbrev.properties#]
